[[redirects]]
  from = "/athlete"
  to = "/athlete/index.html"
  status = 200

[[redirects]]
  from = "/athlete/*"
  to = "/athlete/index.html"
  status = 200

[[redirects]]
  from = "/coach"
  to = "/coach/index.html"
  status = 200
